export {default as registerRouter} from "./register.js"
export {default as loginRouter} from "./login.js"
export {default as logoutRouter} from "./logout.js"
export {default as authRouter} from "./auth.js"
export {default as emailRouter} from "./email.js"
export {default as passwordRouter} from "./password.js"